cookie:
  expiry_days: 30
  key: euskolingo_key
  name: euskolingo_name
credentials:
  usernames:
    abertelsen:
      email: abertelsen@gmail.com
      failed_login_attempts: 0
      first_name: Alvaro
      last_name: Bertelsen
      logged_in: false
      password: $2b$12$ciZgWpNIZby09jZJ8WDEr.cU0hjqOnwpYERy/YZuXtGtgs1/pZGba
      roles:
      - admin
      - editor
      - viewer
    vicomtech:
      email: abertelsen@vicomtech.org
      first_name: Alvaro
      last_name: Bertelsen
      logged_in: false
      password: $2b$12$HWGXTDwT7x0YfvlQXFFGmuBz2b2m947wJy.rzBtwI0KIbSHb.GTtW
      password_hint: '...'
      roles: null
pre-authorized:
  emails: []
