cookie:
  expiry_days: 30
  key: euskolingo_key
  name: euskolingo_name
credentials:
  usernames:
    abertelsen:
      email: abertelsen@gmail.com
      failed_login_attempts: 0
      first_name: Alvaro
      last_name: Bertelsen
      logged_in: false
      password: $2b$12$ciZgWpNIZby09jZJ8WDEr.cU0hjqOnwpYERy/YZuXtGtgs1/pZGba
      roles:
      - admin
      - editor
      - viewer
pre-authorized:
  emails:
  - abertelsen@vicomtech.org
