# .streamlit/secrets.toml
[connections.turso]
url = "sqlite+libsql://euskodb-abertelsen.turso.io/?authToken=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3Mjk2NzIyMDcsImlkIjoiZGRmYjdjODgtZjI5Mi00NzAwLThkN2ItZTZiNjg2MWFiOTEwIn0.7S57U7ipgOph-oLkcVl5VKIJAoPw00btcWOXWKPDfLKPmzSM2qwQuBpBEsRtA-WldfIMf1IujD_x_yERRf7zCQ&secure=True"

[email]
address = "info.hitzon@gmail.com"
password = "..."
